dist: trusty
sudo: required

language: php

php:
  - 5.6

services:
  - docker

cache:
  apt: true
  directories:
    - $TRAVIS_BUILD_DIR/vendor
    - $TRAVIS_BUILD_DIR/tests/node_modules
    - $HOME/.composer/cache

env:
  matrix:
    - TEST_COUNTRY=argentina
    - TEST_COUNTRY=brazil
    - TEST_COUNTRY=chile
    - TEST_COUNTRY=colombia
    - TEST_COUNTRY=ecuador
    - TEST_COUNTRY=mexico
    - TEST_COUNTRY=peru

install: composer update

script:
  - bash ./tests/bin/test.sh

stages:
  - lint
  - unit
  - admin_tests
  - test
  - release
  - deploy

jobs:
  include:
    - stage: lint
      env:
        - TEST_COUNTRY=
      script:
        - travis_wait bash ./.scripts/phpcs.sh
    - stage: unit
      env:
        - TEST_COUNTRY=
      script:
        - phpunit
    - stage: admin_tests
      env:
        - TEST_COUNTRY=
      script:
        - bash ./tests/bin/admin-test.sh
    - stage: release
      script:
        - bash <(curl -s https://codecov.io/bash)
        - bash .scripts/before_deploy.sh
        - cd $TRAVIS_BUILD_DIR
        - zip -r /tmp/ebanx-payment-gateway-for-woocommerce ./* -x "*.git*" "*tests*" "*_vendor*"
      env:
        - TEST_COUNTRY=
      deploy:
        - provider: releases
          api_key:
            secure: EpKgBzXXLjndUmMDZEoaDVel0/dqBEHN3btgVGBThFlMD3/gAouufGNmoYEeEkZXmq7i8Ab9dSaXT6UjVmEL69jKlZIpZ+zOFyDce1F0u7hAZywS3O/N5Y+w6JDW44Q0+7APob0DyCWjWRHOhY706VPU3yTv6Tsd+UL9RUCmIjYvFnU7PKvNChDJEV0fAdKnXiORIFkweq4kswUk0age/BdtyTosDZAkAd2uCM0D271f1pJ9ay1vq8gj4YSdAvjnz/i+HjrkIXPOV808QgSqxj+qEMXnBidjFdiNEQFCFdoYYsNJr67LQdvO1LYMsScyuGiQLTSND4NZ4DWIb6m9bmCy/+YC19mDVrq4ne8f6ZQ57Aqr3EMeU67PybjvLSELp9m7dl3E0NirPeBSRnn7OVLpFiFRhGTRi3jc6mfyi9pWOsrJ97iczSV43D7wfVkeibNrClfzIX6h4nLwlfLq0JISN/5wcJS/ZB4d6QTF28AJwQag6G7o/Fs0vmIHUpquMbNcZ6RsU4XoR+c/x6JBrnvAdHl+hoBKJHbKqciLD7HbTtyI8Su0CcxF8o2WIHPJYjYzwbkLZfCXojrtQfAi7clg5OmioJ/IXeu5e3FsUXetvWQulHfdu7k5eatTgbx7UMEt5kkphpzs7BhMnAYXEDrfuAyfrTHUaAYce1ruTvM=
          file: /tmp/ebanx-payment-gateway-for-woocommerce.zip
          skip_cleanup: true
          on:
            tags: true
            all_branches: true
    - stage: deploy
      script:
        - bash .scripts/before_deploy.sh
      env:
        - TEST_COUNTRY=
      deploy:
        - provider: script
          skip_cleanup: true
          script: ./deploy.sh
          on:
            tags: true
            all_branches: true
