dist: trusty
sudo: required

language: php

php:
  - 5.6

services:
  - docker

cache:
  apt: true
  directories:
    - $TRAVIS_BUILD_DIR/vendor
    - $TRAVIS_BUILD_DIR/tests/node_modules
    - $HOME/.composer/cache

env:
  matrix:
    - TEST_COUNTRY=argentina
    - TEST_COUNTRY=brazil
    - TEST_COUNTRY=chile
    - TEST_COUNTRY=colombia
    - TEST_COUNTRY=ecuador
    - TEST_COUNTRY=mexico
    - TEST_COUNTRY=peru

install: composer update

script:
  - bash ./tests/bin/test.sh

stages:
  - lint
  - unit
  - admin_tests
  - test
  - release
  - deploy

jobs:
  include:
    - stage: lint
      env:
        - TEST_COUNTRY=
      script:
        - travis_wait bash ./.scripts/phpcs.sh
    - stage: unit
      env:
        - TEST_COUNTRY=
      script:
        - phpunit
    - stage: admin_tests
      env:
        - TEST_COUNTRY=
      script:
        - bash ./tests/bin/admin-test.sh
    - stage: release
      script:
        - bash <(curl -s https://codecov.io/bash)
        - bash .scripts/before_deploy.sh
        - cd $TRAVIS_BUILD_DIR
        - zip -r /tmp/ebanx-payment-gateway-for-woocommerce ./* -x "*.git*" "*tests*" "*_vendor*"
      env:
        - TEST_COUNTRY=
      deploy:
        - provider: releases
          api_key:
            secure: EHLRyqTabc0yXKcGk3FHK2xkrmx44CHZL6c8WKF/9LcyoSq4LLAxK98nYpjWNfqNXYAChgaPiUpR1slS/N1s3ExAfpupYqP26c+E/x6vsbQVAGIih/rrOG9trVWKIXqWFBlLAw6O/kp4Dw7/uvfMim0/ti8WRQwUxg2d6q/Y7kSjjbpnuKo7AekYCSgmRdokKupxmo5XBXD0af0HimyJvO+wKoJxvzDq+6Przw+EPE2C19yImbWzI74zepUQuQfxRMUP8Xa5JWwz7V+XQhhxinGb/E66z9kPU/BwNHolz1rEBVR3F/vg9rfKOQxLlg96HNDDsu/cJXIjQpUIjMiYBPoftLVUzAm2fk9ksi4iWc/adRM1nWIxq1OyGp5toJBUgBwogS48EF0TP2OysrTj9qiWvVT5kY3Lk+YeRW4yN8AmeSko8tHCZ6xkE5CcGcFmV07YM+JK9lcgjpEAa7oZr64nDrHCLZz9nnhR/Y81cQWCKFEJITULFZOWxF5qxm4HpwxUnJgdEompH9eeHDh/sCl/86GkN3jQ2q7r6cVfZC7tR3008r8K6fMkoCkiU10ZsIP4URSf2C+GoS45VPPcyrKK5268cjDh1WyCD9qtRHScFsYf2YA7nBOi9JINOjV2btyJ6Ol4X/kBPmxlxGM98pl0kwoEG0gzHH6ADiRpoQs=
          file: /tmp/ebanx-payment-gateway-for-woocommerce.zip
          skip_cleanup: true
          on:
            tags: true
            all_branches: true
    - stage: deploy
      script:
        - bash .scripts/before_deploy.sh
      env:
        - TEST_COUNTRY=
      deploy:
        - provider: script
          skip_cleanup: true
          script: ./deploy.sh
          on:
            tags: true
            all_branches: true
