dist: trusty
sudo: required

language: php

php:
  - 5.6

services:
  - docker

cache:
  apt: true
  directories:
    - $TRAVIS_BUILD_DIR/vendor
    - $TRAVIS_BUILD_DIR/tests/node_modules
    - $HOME/.composer/cache

env:
  matrix:
    - TEST_COUNTRY=argentina
    - TEST_COUNTRY=brazil
    - TEST_COUNTRY=chile
    - TEST_COUNTRY=colombia
    - TEST_COUNTRY=ecuador
    - TEST_COUNTRY=mexico
    - TEST_COUNTRY=peru

install: composer update

script:
  - bash ./tests/bin/test.sh

stages:
  - lint
  - unit
  - test
  - release
  - deploy

jobs:
  include:
    - stage: lint
      env:
        - TEST_COUNTRY=
      script:
        - bash .scripts/phpcs.sh
    - stage: unit
      env:
        - TEST_COUNTRY=
      script:
        - phpunit
    - stage: release
      script:
        - bash <(curl -s https://codecov.io/bash)
        - bash .scripts/before_deploy.sh
        - cd $TRAVIS_BUILD_DIR
        - zip -r /tmp/ebanx-payment-gateway-for-woocommerce ./* -x "*.git*" "*tests*" "*_vendor*"
      env:
        - TEST_COUNTRY=
      deploy:
        - provider: releases
          api_key:
            secure: nZpLHPhz3gYdig3tiKfqD/aykGF9qjwzpDsqtCGxHAY52N6/nqUi+kzMluOGvYLxp93VpKaupAXMUDtZ26mf+fVi3Be+lfm+lnzZjg96ZzwcUYX8RIrDNwjXkt63UCyFX8wCt6XXn7l9xlL3wnqTzkxWik+ODt/oFJ70OFT8pfRZi6sR7kIgwnxb/nE+S3nf6jaoglywHq/d3OumQYfGbxnqf/7M7uhjSJXHAZGZFxue8m4RmpuV2su/3LaSElFkmMVv8PB3pplJxDeP/KDMjHk+e3T6LH0AXcYRFhIoUpTPbQj/0jWyUv0S8rncv9l7b+YHcRsOpwriewBDy+NQDKQpGd8MI2KmK1WirFkx8yTu1pXZBXk3D4WGxNdtaf6jdBFs4y+TM2/L6/ObaELosvqzp57CtRsVYuQ/sweQPhmngY0JJ7aDTR6XAwey31G39oYiPOhcRCRq3CEntLEEG26yB0a3soWoG+7I0U65HF093WKR/NujUn3HAPRGDrqHCmA2CoU7ut5CoGRFHDe8qTN4PnfvvAn5L6r0HJRRdwNbtcP5lsGzdKlwUNL/vq5M9BhRyx93Umy8KAl/LtP43NGDeA9KvOCRIkuSvrLHKd/xbUsnOjsxTbhpN6w8rCIqLFflR8GywXoUFnnlV48hRiDXgTjV9vMyhfIoB484ino=
          file: /tmp/ebanx-payment-gateway-for-woocommerce.zip
          skip_cleanup: true
          on:
            tags: true
            all_branches: true
    - stage: deploy
      script:
        - bash .scripts/before_deploy.sh
      env:
        - TEST_COUNTRY=
      deploy:
        - provider: script
          skip_cleanup: true
          script: ./deploy.sh
          on:
            tags: true
            all_branches: true
